name: dagger

on:
  push:
    branches: [main]

jobs:
  runllm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # is Docker needed?
      # uses: docker/setup-docker-action@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: functions
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
